### ISSUE TITLE
Outsanding issues / minor bugs

### ISSUE THREAD

**Issue by SeloSlav** [SeloSlav/FarmersFable#27]
Anything else to add?

As for me:

* ~~When Yonatan provides the new pre-determined trajectories up to 500 harvests I will implement those throughout.~~
* ~~Show numbers next to bundles in detailed computation.~~
* ~~Remove clicking sound when changing slides? Add clicking sound to key press?~~

**Comment by SeloSlav** [comment]
Update. The following will take me more time I expected:

* ~~Add umlauts to vowels in German translation (font is translated from a graphic so must add umlauts to font graphic)~~
* ~~Fix spacing issue for special German characters~~
* ~~Change labels on graphs to German (The current JavaScript chart labels are not dynamically changeable based on German/English language selection at intro screen - need to instantiate new charts where labels 'Cooperating' and 'Alone' exist)~~
* ~~Change side menu to German~~

**Comment by SeloSlav** [comment]
@Marcthewriter I'm trying to find a solution to the spacing issue. I asked people on the Construct forum. The alternative of producing graphics for each text is far too labor intensive (and would slow down the user experience) so I'd prefer to avoid it. I think I should have something in a few days.

**Comment by Marcthewriter** [comment]
So should we for now have the English edition ready (without the choice for English and German on the starting page) and online and add the German version(s) once you found a solution? 
Since farmersfable.org is linked to the animation already, currently everyone who looks it up can follow our experiments...

**Comment by SeloSlav** [comment]
> 
> 
> So should we for now have the English edition ready (without the choice for English and German on the starting page) and online and add the German version(s) once you found a solution?
> Since farmersfable.org is linked to the animation already, currently everyone who looks it up can follow our experiments...

Check it out. I managed to find a fix for all umlaut and spacing issues!

**Comment by Marcthewriter** [comment]
Great! Looks good, apart from some minor issues!

**Comment by SeloSlav** [comment]
I've pushed about 5 updates since you've checked most likely. Have another look and let me know if there are any remaining issues.

**Comment by Marcthewriter** [comment]
Right. I see. Not much left :-)

**Comment by Marcthewriter** [comment]
On this slide, the link-line seems to be somehow out of place

![Bildschirmfoto 2019-05-25 um 23 10 55](https://user-images.githubusercontent.com/50121811/58374761-e8fde300-7f43-11e9-8af9-2c742f05bf4f.png)
***
On this slide I made a translation error. Sorry! 
The first word of the lower paragraph is not "Es" but "Sie".

![Bildschirmfoto 2019-05-25 um 23 17 41](https://user-images.githubusercontent.com/50121811/58374813-067f7c80-7f45-11e9-9795-28e581c9fa26.jpg)

***
On this slide there is some text missing at the end of the first paragraph. The whole text would be

**This mathematical insight is absent from modern economics, whose foundations were laid in the 18th century when mathematics itself was still in its infancy.** /
Diese mathematische Erkenntnis fehlt in der modernen Ökonomik, deren Grundlagen im 18. Jahrhundert gelegt wurden, als auch die Mathematik noch in ihren **Kinderschuhen steckte**_(missing)_.

![Bildschirmfoto 2019-05-25 um 23 13 03](https://user-images.githubusercontent.com/50121811/58374769-134fa080-7f44-11e9-9b3e-7b2f5a8e59f9.png)
***

**Comment by SeloSlav** [comment]
> 
> 
> On this slide, the link-line seems to be somehow out of place
> 
> ![Bildschirmfoto 2019-05-25 um 23 10 55](https://user-images.githubusercontent.com/50121811/58374761-e8fde300-7f43-11e9-8af9-2c742f05bf4f.png)
> 
> On this slide I made a translation error. Sorry!
> The first word of the lower paragraph is not "Es" but "Sie".
> 
> ![Bildschirmfoto 2019-05-25 um 23 17 41](https://user-images.githubusercontent.com/50121811/58374813-067f7c80-7f45-11e9-9795-28e581c9fa26.jpg)
> 
> On this slide there is some text missing at the end of the first paragraph. The whole text would be
> 
> **This mathematical insight is absent from modern economics, whose foundations were laid in the 18th century when mathematics itself was still in its infancy.** /
> Diese mathematische Erkenntnis fehlt in der modernen Ökonomik, deren Grundlagen im 18. Jahrhundert gelegt wurden, als auch die Mathematik noch in ihren **Kinderschuhen steckte**_(missing)_.
> 
> ![Bildschirmfoto 2019-05-25 um 23 13 03](https://user-images.githubusercontent.com/50121811/58374769-134fa080-7f44-11e9-9b3e-7b2f5a8e59f9.png)

All fixed. Pushing an update in one minute...

**Comment by Marcthewriter** [comment]
And then there would still be the flag issue.

They are a bit big. Could they have a size so they end with the respective line of the respective language, like in the layout? Marked it with green lines.

And with the flags we no longer need (English) and (Deutsch) at the end of the options.

![Index_flag2_green](https://user-images.githubusercontent.com/50121811/58212057-df7b3d80-7ced-11e9-9f51-30e6baf5cf4b.jpg)

**Comment by SeloSlav** [comment]
> 
> 
> And then there would still be the flag issue.
> 
> They are a bit big. Could they have a size so they end with the respective line of the respective language, like in the layout? Marked it with green lines.
> 
> And with the flags we no longer need (English) and (Deutsch) at the end of the options.
> 
> ![Index_flag2_green](https://user-images.githubusercontent.com/50121811/58212057-df7b3d80-7ced-11e9-9f51-30e6baf5cf4b.jpg)

Done!

**Comment by Marcthewriter** [comment]
Can't believe it! Are we really done (almost)? 

I'll check it again and if I don't find anything, I'll make the movies, and send you the YouTube-Links tomorrow.

**Comment by SeloSlav** [comment]
> 
> 
> Can't believe it! Are we really done (almost)?
> 
> I'll check it again and if I don't find anything, I'll make the movies, and send you the YouTube-Links tomorrow.

I believe we're almost there! Have a look through and let me know what's missing. Cheers.

**Comment by SeloSlav** [comment]
@Marcthewriter 

Ah. What's missing is that labels on the charts. They're still in English even when we're in German mode. Unfortunately, this is not a trivial fix and will take a few days...

![image](https://user-images.githubusercontent.com/8828948/58374908-22aafb80-7efc-11e9-8b75-4822ef2a2c96.png)

**Comment by Marcthewriter** [comment]
> @Marcthewriter
> 
> Ah. What's missing is that labels on the charts. They're still in English even when we're in German mode. Unfortunately, this is not a trivial fix and will take a few days...
> 
> ![image](https://user-images.githubusercontent.com/8828948/58374908-22aafb80-7efc-11e9-8b75-4822ef2a2c96.png)

:-/ Well, there had to be something ...

**Comment by Marcthewriter** [comment]
![Bildschirmfoto 2019-05-25 um 23 54 27](https://user-images.githubusercontent.com/50121811/58374944-83602580-7f48-11e9-94ee-10afde2e3a17.png)

At the slide with the King's chessboard 

> The process is faster than what most people guess. Remember the story about the king's chessboard? /
> **Das geht schneller, als die meisten Menschen glauben. Wie bei der Geschichte mit den Reiskörnern auf dem Schachbrett.**

of course we need to link to a German site:
https://de.wikipedia.org/wiki/Sissa_ibn_Dahir#Legende

**Comment by SeloSlav** [comment]
> 
> 
> At the slide with the King's chessboard
> 
> > The process is faster than what most people guess. Remember the story about the king's chessboard? /
> > **Das geht schneller, als die meisten Menschen glauben. Wie bei der Geschichte mit den Reiskörnern auf dem Schachbrett.**
> 
> of course we need to link to a German site:
> https://de.wikipedia.org/wiki/Sissa_ibn_Dahir#Legende

Yes. Noticed that. Fixed it.

**Comment by Marcthewriter** [comment]
> > At the slide with the King's chessboard
> > > The process is faster than what most people guess. Remember the story about the king's chessboard? /
> > > **Das geht schneller, als die meisten Menschen glauben. Wie bei der Geschichte mit den Reiskörnern auf dem Schachbrett.**
> > 
> > 
> > of course we need to link to a German site:
> > https://de.wikipedia.org/wiki/Sissa_ibn_Dahir#Legende
> 
> Yes. Noticed that. Fixed it.

👍

**Comment by Marcthewriter** [comment]
Found one minor mistake in the english version: 

It needs to be "... Good and bad seasons ...". 
seasons with an s at the end.

![Bildschirmfoto 2019-05-26 um 12 57 00](https://user-images.githubusercontent.com/50121811/58380797-dfad5e80-7fb5-11e9-84e7-214b88644b2a.png)

**Comment by SeloSlav** [comment]
Thanks. I'll fix that.

@Marcthewriter A better alternative to translating the labels in the charts themselves might be to remove them altogether and do something like this:

![image](https://user-images.githubusercontent.com/8828948/58385563-18920700-7fa7-11e9-81c5-7007b91bab2f.png)

This would be a very simple fix and would not require messing with the chart configuration files. It would also potentially make the charts readable on mobile since the labels take up a lot of space.

Would you be okay with this? Difference is 1 hr implementation vs something like 10.

**Comment by Marcthewriter** [comment]
Ok with me. Only in the German version, I guess?

**Comment by SeloSlav** [comment]
> 
> 
> Ok with me. Only in the German version, I guess?

It would be for both. It's all actually the same code base, but there is a 'flag variable' that tells the software to show German or English translations depending on what language it is set to.

**Comment by SeloSlav** [comment]
@Marcthewriter Check it out now. I actually think this looks better anyway!

![image](https://user-images.githubusercontent.com/8828948/58386070-6e6aad00-7faf-11e9-8d6d-b9980f669e8b.png)

**Comment by SeloSlav** [comment]
@Marcthewriter 

This is what it looks like for me on mobile when I rotate my screen (landscape):

![image](https://user-images.githubusercontent.com/8828948/58386127-1aac9380-7fb0-11e9-96d2-dad388bc18d7.png)

![image](https://user-images.githubusercontent.com/8828948/58386129-1c765700-7fb0-11e9-8fcc-bd9205933b58.png)

![image](https://user-images.githubusercontent.com/8828948/58386132-1ed8b100-7fb0-11e9-8468-8f300381f541.png)

Not bad actually! If we actually remove "Harvest" from each tick on the X axis it would be even more readable. Here's a mockup:

![image](https://user-images.githubusercontent.com/8828948/58386161-71b26880-7fb0-11e9-8d5c-9946f1bdfcf4.png)


What do you think?

**Comment by Marcthewriter** [comment]
> @Marcthewriter Check it out now. I actually think this looks better anyway!
> 
> ![image](https://user-images.githubusercontent.com/8828948/58386070-6e6aad00-7faf-11e9-8d6d-b9980f669e8b.png)

Looks good! 

Though I spent hours today to create the English movie lol! Nevermind.

**Comment by SeloSlav** [comment]
> 
> 
> > @Marcthewriter Check it out now. I actually think this looks better anyway!
> > ![image](https://user-images.githubusercontent.com/8828948/58386070-6e6aad00-7faf-11e9-8d6d-b9980f669e8b.png)
> 
> Looks good!
> 
> Though I spent hours today to create the English movie lol! Nevermind.

My apologies! I won't make any more changes.

**Comment by Marcthewriter** [comment]
> @Marcthewriter
> 
> This is what it looks like for me on mobile when I rotate my screen (landscape):
> 
> ![image](https://user-images.githubusercontent.com/8828948/58386132-1ed8b100-7fb0-11e9-8468-8f300381f541.png)
> 
> Not bad actually! If we actually remove "Harvest" from each tick on the X axis it would be even more readable. Here's a mockup:
> 
> ![image](https://user-images.githubusercontent.com/8828948/58386161-71b26880-7fb0-11e9-8d5c-9946f1bdfcf4.png)
> 
> What do you think?

Looks good. The lines are too thick for the small mobile screen. And on mine (iPhone 6s) it looks like this



> > > @Marcthewriter Check it out now. I actually think this looks better anyway!
> > > ![image](https://user-images.githubusercontent.com/8828948/58386070-6e6aad00-7faf-11e9-8d6d-b9980f669e8b.png)
> > 
> > 
> > Looks good!
> > Though I spent hours today to create the English movie lol! Nevermind.
> 
> My apologies! I won't make any more changes.

Non, no! It's ok!

**Comment by Marcthewriter** [comment]
> @Marcthewriter Check it out now. I actually think this looks better anyway!
> 
> ![image](https://user-images.githubusercontent.com/8828948/58386070-6e6aad00-7faf-11e9-8d6d-b9980f669e8b.png)

On my iPhone 6s it looks like this:

![IMG_7545](https://user-images.githubusercontent.com/50121811/58386643-0c3b9780-8003-11e9-955d-45cf4afb82ac.png)
![IMG_7546](https://user-images.githubusercontent.com/50121811/58386644-0c3b9780-8003-11e9-84bb-911f0db2f494.png)
![IMG_7548](https://user-images.githubusercontent.com/50121811/58386646-0d6cc480-8003-11e9-86d9-6ed6cfad76ea.png)
![IMG_7549](https://user-images.githubusercontent.com/50121811/58386647-0d6cc480-8003-11e9-8613-fbe51a4c3b9c.png)
![IMG_7547](https://user-images.githubusercontent.com/50121811/58386648-0e055b00-8003-11e9-8880-b53f9fad6fdd.png)

**Comment by SeloSlav** [comment]
Fair enough. Given all the different phone types I don't think this is a solution then. I won't be able to develop mobile support for this. It's a large project. For me, on my LG Android phone it looks pretty good when I rotate to landscape orientation...

**Comment by Marcthewriter** [comment]
> Fair enough. Given all the different phone types I don't think this is a solution then. I won't be able to develop mobile support for this. It's a large project. For me, on my LG Android phone it looks pretty good when I rotate to landscape orientation...

A pity! So I guess we'll go with the videos ...

**Comment by SeloSlav** [comment]
Yes. As far as I'm concerned Farmers Fable looks done!

**Comment by Marcthewriter** [comment]
I'll check. If I don't find anything I'll record the German video and sent you the YouTube-Link for the videos once I've uploaded them. To insert them into the starting slide

**Comment by SeloSlav** [comment]
> 
> 
> I'll check. If I don't find anything I'll record the German video and sent you the YouTube-Link for the videos once I've uploaded them. To insert them into the starting slide

Sounds good!

**Comment by Marcthewriter** [comment]
Here are the links for the startpage to the videos on YouTube:

English
https://youtu.be/8_iRv95qgi8

German
https://youtu.be/9laBsCfJ4FY

And - done!

**Comment by SeloSlav** [comment]
> 
> 
> Here are the links for the startpage to the videos on YouTube:
> 
> English
> https://youtu.be/8_iRv95qgi8
> 
> German
> https://youtu.be/9laBsCfJ4FY
> 
> And - done!

Awesome. Done!

**Comment by Marcthewriter** [comment]
> > Here are the links for the startpage to the videos on YouTube:
> > English
> > https://youtu.be/8_iRv95qgi8
> > German
> > https://youtu.be/9laBsCfJ4FY
> > And - done!
> 
> Awesome. Done!

Thx!

**Comment by Marcthewriter** [comment]
Problem is: if I tab the links on my phone, nothing happens ... I am not forwarded to YouTube

**Comment by SeloSlav** [comment]
> 
> 
> Problem is: if I tab the links on my phone, nothing happens ... I am not forwarded to YouTube

Yikes. May have to clear cache on phone as well. Works for me. I wonder if we should provide a warning on the intro screen... Then again, all the bugs should be fixed now, so publicizing it shouldn't be a problem.

**Comment by Marcthewriter** [comment]
Sorry, after clearing cache on phone still doesn't work. BTW neither on the ipad (which isn't such a problem since one can use the animation - but the other links in the animation neither work on the pad)
